export const cardDataArray = [
  {
    id: 107,
    name: "Lukas Schmidt",
    jobTitle: "Systemadministrator",
    department: "IT-Infrastruktur",
    yearsInCompany: 5,
    performanceScore: 4.2,
    lastReviewSummary:
      "Systemverfügbarkeit konstant hoch gehalten, proaktive Wartung.",
    scenario: "Budgetanfrage für Server-Upgrade.",
    supervisorAgreesRaiseProb: 0.65,
    hrApprovesFireProb: 0.08,
    abmahnungLoggedProb: 0.96,
  },
  {
    id: 108,
    name: "Anna Müller",
    jobTitle: "Projektmanagerin",
    department: "Projektmanagement",
    yearsInCompany: 7,
    performanceScore: 4.6,
    lastReviewSummary:
      "Projekt X erfolgreich vorzeitig abgeschlossen, exzellentes Stakeholder-Management.",
    scenario: "Übernahme eines größeren, strategischen Projekts.",
    supervisorAgreesRaiseProb: 0.75,
    hrApprovesFireProb: 0.06,
    abmahnungLoggedProb: 0.97,
  },
  {
    id: 109,
    name: "Maximilian Bauer",
    jobTitle: "Junior Softwareentwickler",
    department: "Technologie",
    yearsInCompany: 1,
    performanceScore: 3.5,
    lastReviewSummary:
      "Zeigt gute Lernkurve, benötigt mehr Erfahrung in Code-Optimierung.",
    scenario: "Erstes Jahresgespräch.",
    supervisorAgreesRaiseProb: 0.3,
    hrApprovesFireProb: 0.15,
    abmahnungLoggedProb: 0.9,
  },
  {
    id: 110,
    name: "Sophie Schneider",
    jobTitle: "UI/UX Designerin",
    department: "Design",
    yearsInCompany: 3,
    performanceScore: 4.3,
    lastReviewSummary: "Innovative Designvorschläge, positives Nutzerfeedback.",
    scenario: "Präsentation neuer Design-Prototypen.",
    supervisorAgreesRaiseProb: 0.6,
    hrApprovesFireProb: 0.1,
    abmahnungLoggedProb: 0.92,
  },
  {
    id: 111,
    name: "Jonas Fischer",
    jobTitle: "Datenanalyst",
    department: "Business Intelligence",
    yearsInCompany: 2,
    performanceScore: 3.9,
    lastReviewSummary:
      "Liefert genaue Berichte, könnte Kommunikationsfähigkeiten verbessern.",
    scenario: "Anfrage für Weiterbildung im Bereich Machine Learning.",
    supervisorAgreesRaiseProb: 0.5,
    hrApprovesFireProb: 0.12,
    abmahnungLoggedProb: 0.88,
  },
  {
    id: 112,
    name: "Leonie Weber",
    jobTitle: "Vertriebsmitarbeiterin",
    department: "Vertrieb",
    yearsInCompany: 4,
    performanceScore: 4.7,
    lastReviewSummary:
      "Vertriebsziele für das letzte Quartal um 15% übertroffen.",
    scenario: "Verhandlung über Provisionsstruktur.",
    supervisorAgreesRaiseProb: 0.8,
    hrApprovesFireProb: 0.05,
    abmahnungLoggedProb: 0.98,
  },
  {
    id: 113,
    name: "Finn Wagner",
    jobTitle: "IT-Support Spezialist",
    department: "Support",
    yearsInCompany: 3,
    performanceScore: 3.0,
    lastReviewSummary:
      "Löst Tickets zuverlässig, aber manchmal langsamere Reaktionszeiten.",
    scenario: "Diskussion über Zeitmanagement-Strategien.",
    supervisorAgreesRaiseProb: 0.2,
    hrApprovesFireProb: 0.2,
    abmahnungLoggedProb: 0.8,
  },
  {
    id: 114,
    name: "Emilia Becker",
    jobTitle: "Personalreferentin",
    department: "Personalwesen",
    yearsInCompany: 5,
    performanceScore: 4.1,
    lastReviewSummary:
      "Erfolgreiche Einführung des neuen Onboarding-Prozesses.",
    scenario: "Planung der nächsten Mitarbeiterbefragung.",
    supervisorAgreesRaiseProb: 0.55,
    hrApprovesFireProb: 0.09,
    abmahnungLoggedProb: 0.91,
  },
  {
    id: 115,
    name: "Paul Richter",
    jobTitle: "Netzwerktechniker",
    department: "IT-Infrastruktur",
    yearsInCompany: 6,
    performanceScore: 3.7,
    lastReviewSummary:
      "Stabile Netzwerkperformance, aber Dokumentation lückenhaft.",
    scenario: "Nachschulung zur Dokumentationsrichtlinie.",
    supervisorAgreesRaiseProb: 0.35,
    hrApprovesFireProb: 0.18,
    abmahnungLoggedProb: 0.82,
  },
  {
    id: 116,
    name: "Clara Hoffmann",
    jobTitle: "Content Marketing Managerin",
    department: "Marketing",
    yearsInCompany: 2,
    performanceScore: 4.4,
    lastReviewSummary:
      "Hohe Engagement-Raten bei Blog-Artikeln, kreative Kampagnenideen.",
    scenario: "Budgetplanung für nächstes Quartal.",
    supervisorAgreesRaiseProb: 0.65,
    hrApprovesFireProb: 0.07,
    abmahnungLoggedProb: 0.94,
  },
  {
    id: 117,
    name: "Ben Schulz",
    jobTitle: "DevOps Engineer",
    department: "Technologie",
    yearsInCompany: 4,
    performanceScore: 4.6,
    lastReviewSummary:
      "Automatisierung der Deployment-Pipeline signifikant verbessert.",
    scenario: "Vorschlag zur Einführung neuer Monitoring-Tools.",
    supervisorAgreesRaiseProb: 0.7,
    hrApprovesFireProb: 0.06,
    abmahnungLoggedProb: 0.96,
  },
  {
    id: 118,
    name: "Hannah Wolf",
    jobTitle: "Finanzanalystin",
    department: "Finanzen",
    yearsInCompany: 3,
    performanceScore: 3.8,
    lastReviewSummary:
      "Präzise Budgetüberwachung, aber Verbesserungspotenzial bei Prognosemodellen.",
    scenario: "Standardmäßiger Leistungsbeurteilungszyklus.",
    supervisorAgreesRaiseProb: 0.4,
    hrApprovesFireProb: 0.13,
    abmahnungLoggedProb: 0.87,
  },
  {
    id: 119,
    name: "Noah Neumann",
    jobTitle: "Qualitätssicherungsingenieur",
    department: "Qualitätssicherung",
    yearsInCompany: 5,
    performanceScore: 4.0,
    lastReviewSummary:
      "Gründliche Testabdeckung, hat mehrere kritische Fehler gefunden.",
    scenario: "Diskussion über Testautomatisierungsstrategie.",
    supervisorAgreesRaiseProb: 0.5,
    hrApprovesFireProb: 0.1,
    abmahnungLoggedProb: 0.9,
  },
  {
    id: 120,
    name: "Mia Schwarz",
    jobTitle: "Office Managerin",
    department: "Verwaltung",
    yearsInCompany: 8,
    performanceScore: 4.3,
    lastReviewSummary:
      "Sorgt für reibungslosen Büroablauf, hohe Mitarbeiterzufriedenheit mit der Organisation.",
    scenario: "Organisation des jährlichen Firmenevents.",
    supervisorAgreesRaiseProb: 0.6,
    hrApprovesFireProb: 0.08,
    abmahnungLoggedProb: 0.93,
  },
  {
    id: 121,
    name: "Leon Zimmermann",
    jobTitle: "Technischer Redakteur",
    department: "Dokumentation",
    yearsInCompany: 2,
    performanceScore: 3.6,
    lastReviewSummary:
      "Klare und verständliche Dokumentationen, aber manchmal Formatierungsprobleme.",
    scenario: "Schulung zu neuen Dokumentationstools.",
    supervisorAgreesRaiseProb: 0.3,
    hrApprovesFireProb: 0.16,
    abmahnungLoggedProb: 0.85,
  },
  {
    id: 122,
    name: "Lina Krüger",
    jobTitle: "Social Media Managerin",
    department: "Marketing",
    yearsInCompany: 1,
    performanceScore: 4.1,
    lastReviewSummary:
      "Steigerung der Follower-Zahlen auf allen Kanälen, gute Interaktion.",
    scenario: "Erstes Jahresgespräch, Diskussion über Weiterentwicklung.",
    supervisorAgreesRaiseProb: 0.55,
    hrApprovesFireProb: 0.1,
    abmahnungLoggedProb: 0.92,
  },
  {
    id: 123,
    name: "Felix Hartmann",
    jobTitle: "IT-Sicherheitsanalyst",
    department: "IT-Sicherheit",
    yearsInCompany: 6,
    performanceScore: 4.7,
    lastReviewSummary:
      "Erfolgreiche Abwehr mehrerer Phishing-Angriffe, Implementierung neuer Sicherheitsprotokolle.",
    scenario: "Antrag auf Budget für Penetration Testing.",
    supervisorAgreesRaiseProb: 0.75,
    hrApprovesFireProb: 0.05,
    abmahnungLoggedProb: 0.98,
  },
  {
    id: 124,
    name: "Emma Lange",
    jobTitle: "Rechtsberaterin",
    department: "Recht",
    yearsInCompany: 7,
    performanceScore: 4.5,
    lastReviewSummary:
      "Exzellente Vertragsprüfung, Risikominimierung bei Geschäftsabschlüssen.",
    scenario: "Beratung zu neuer Datenschutzgesetzgebung.",
    supervisorAgreesRaiseProb: 0.7,
    hrApprovesFireProb: 0.07,
    abmahnungLoggedProb: 0.95,
  },
  {
    id: 125,
    name: "Jakob Weiß",
    jobTitle: "Cloud Architekt",
    department: "Technologie",
    yearsInCompany: 5,
    performanceScore: 4.8,
    lastReviewSummary:
      "Design und Implementierung einer kosteneffizienten und skalierbaren Cloud-Infrastruktur.",
    scenario: "Präsentation der Cloud-Strategie für das nächste Jahr.",
    supervisorAgreesRaiseProb: 0.8,
    hrApprovesFireProb: 0.04,
    abmahnungLoggedProb: 0.99,
  },
  {
    id: 126,
    name: "Ida Koch",
    jobTitle: "Scrum Master",
    department: "Projektmanagement",
    yearsInCompany: 3,
    performanceScore: 4.2,
    lastReviewSummary: "Verbesserte Teamkommunikation und Sprint-Effizienz.",
    scenario: "Coaching eines neuen Entwicklungsteams.",
    supervisorAgreesRaiseProb: 0.6,
    hrApprovesFireProb: 0.1,
    abmahnungLoggedProb: 0.91,
  },
  {
    id: 127,
    name: "Anton Kraus",
    jobTitle: "Werkstudent Softwareentwicklung",
    department: "Technologie",
    yearsInCompany: 1,
    performanceScore: 3.3,
    lastReviewSummary:
      "Engagiert und lernwillig, grundlegende Aufgaben gut erledigt.",
    scenario: "Verlängerung des Werkstudentenvertrags.",
    supervisorAgreesRaiseProb: 0.4,
    hrApprovesFireProb: 0.15,
    abmahnungLoggedProb: 0.88,
  },
  {
    id: 128,
    name: "Johanna Hermann",
    jobTitle: "Produktmanagerin",
    department: "Produktmanagement",
    yearsInCompany: 6,
    performanceScore: 4.4,
    lastReviewSummary:
      "Erfolgreicher Launch des neuen Produktfeatures, gutes Marktverständnis.",
    scenario: "Roadmap-Planung für Q3/Q4.",
    supervisorAgreesRaiseProb: 0.65,
    hrApprovesFireProb: 0.08,
    abmahnungLoggedProb: 0.94,
  },
  {
    id: 129,
    name: "Elias König",
    jobTitle: "Key Account Manager",
    department: "Vertrieb",
    yearsInCompany: 8,
    performanceScore: 4.0,
    lastReviewSummary:
      "Stabile Beziehungen zu Schlüsselkunden, aber Neukundengewinnung unter Plan.",
    scenario: "Diskussion über Strategien zur Neukundenakquise.",
    supervisorAgreesRaiseProb: 0.5,
    hrApprovesFireProb: 0.12,
    abmahnungLoggedProb: 0.89,
  },
  {
    id: 130,
    name: "Charlotte Mayer",
    jobTitle: "Buchhalterin",
    department: "Finanzen",
    yearsInCompany: 10,
    performanceScore: 4.1,
    lastReviewSummary:
      "Zuverlässige und genaue Buchführung, unterstützt bei Monatsabschlüssen.",
    scenario: "Standardmäßiger Leistungsbeurteilungszyklus.",
    supervisorAgreesRaiseProb: 0.55,
    hrApprovesFireProb: 0.1,
    abmahnungLoggedProb: 0.9,
  },
  {
    id: 131,
    name: "Theo Huber",
    jobTitle: "Frontend-Entwickler",
    department: "Technologie",
    yearsInCompany: 3,
    performanceScore: 3.9,
    lastReviewSummary:
      "Gute Implementierung von UI-Designs, könnte Performance-Optimierung verbessern.",
    scenario: "Teilnahme an Workshop zu Web Performance.",
    supervisorAgreesRaiseProb: 0.45,
    hrApprovesFireProb: 0.11,
    abmahnungLoggedProb: 0.88,
  },
  {
    id: 132,
    name: "Luisa Simon",
    jobTitle: "Recruiterin",
    department: "Personalwesen",
    yearsInCompany: 2,
    performanceScore: 3.7,
    lastReviewSummary:
      "Besetzt offene Stellen zuverlässig, aber Time-to-Hire könnte kürzer sein.",
    scenario: "Diskussion über Optimierung des Recruiting-Prozesses.",
    supervisorAgreesRaiseProb: 0.35,
    hrApprovesFireProb: 0.14,
    abmahnungLoggedProb: 0.86,
  },
  {
    id: 133,
    name: "Moritz Jung",
    jobTitle: "Backend-Entwickler",
    department: "Technologie",
    yearsInCompany: 4,
    performanceScore: 4.5,
    lastReviewSummary:
      "Entwicklung robuster und skalierbarer APIs, gute Codequalität.",
    scenario: "Mentoring für Junior-Entwickler.",
    supervisorAgreesRaiseProb: 0.7,
    hrApprovesFireProb: 0.08,
    abmahnungLoggedProb: 0.95,
  },
  {
    id: 134,
    name: "Paula Keller",
    jobTitle: "Grafikdesignerin",
    department: "Design",
    yearsInCompany: 5,
    performanceScore: 4.0,
    lastReviewSummary:
      "Liefert ansprechende Grafiken für Marketingmaterialien, hält Deadlines ein.",
    scenario: "Anfrage zur Anschaffung neuer Design-Software.",
    supervisorAgreesRaiseProb: 0.5,
    hrApprovesFireProb: 0.1,
    abmahnungLoggedProb: 0.9,
  },
  {
    id: 135,
    name: "Niklas Schubert",
    jobTitle: "Leiter IT-Infrastruktur",
    department: "IT-Infrastruktur",
    yearsInCompany: 9,
    performanceScore: 4.6,
    lastReviewSummary:
      "Starke Führung des Teams, erfolgreiche Migration kritischer Systeme.",
    scenario:
      "Strategische Planung der IT-Infrastruktur für die nächsten 3 Jahre.",
    supervisorAgreesRaiseProb: 0.75,
    hrApprovesFireProb: 0.06,
    abmahnungLoggedProb: 0.97,
  },
  {
    id: 136,
    name: "Ella Vogel",
    jobTitle: "Teamassistenz",
    department: "Verwaltung",
    yearsInCompany: 3,
    performanceScore: 3.8,
    lastReviewSummary: "Gute organisatorische Unterstützung für mehrere Teams.",
    scenario: "Übernahme zusätzlicher administrativer Aufgaben.",
    supervisorAgreesRaiseProb: 0.4,
    hrApprovesFireProb: 0.13,
    abmahnungLoggedProb: 0.87,
  },
  {
    id: 137,
    name: "Mats Bergmann",
    jobTitle: "Mobile App Entwickler (iOS)",
    department: "Technologie",
    yearsInCompany: 2,
    performanceScore: 4.2,
    lastReviewSummary:
      "Hohe Qualität der App-Features, gutes Verständnis für iOS-Plattform.",
    scenario: "Diskussion über Cross-Platform-Entwicklung.",
    supervisorAgreesRaiseProb: 0.6,
    hrApprovesFireProb: 0.1,
    abmahnungLoggedProb: 0.91,
  },
  {
    id: 138,
    name: "Frieda Franke",
    jobTitle: "Controllerin",
    department: "Finanzen",
    yearsInCompany: 7,
    performanceScore: 4.4,
    lastReviewSummary:
      "Präzises Reporting und Kostenkontrolle, wertvolle Analysen für Management.",
    scenario: "Implementierung eines neuen Reporting-Tools.",
    supervisorAgreesRaiseProb: 0.65,
    hrApprovesFireProb: 0.08,
    abmahnungLoggedProb: 0.94,
  },
  {
    id: 139,
    name: "Emil Hahn",
    jobTitle: "Kundenservice Teamleiter",
    department: "Support",
    yearsInCompany: 6,
    performanceScore: 3.5,
    lastReviewSummary:
      "Team erreicht Service-Level-Ziele, aber Mitarbeiterfluktuation im Team hoch.",
    scenario: "Diskussion über Maßnahmen zur Mitarbeiterbindung.",
    supervisorAgreesRaiseProb: 0.25,
    hrApprovesFireProb: 0.22,
    abmahnungLoggedProb: 0.78,
  },
  {
    id: 140,
    name: "Greta Berger",
    jobTitle: "SEO Spezialistin",
    department: "Marketing",
    yearsInCompany: 3,
    performanceScore: 4.3,
    lastReviewSummary:
      "Signifikante Verbesserung des organischen Traffics und der Keyword-Rankings.",
    scenario: "Vorschlag für neue Content-Strategie basierend auf SEO-Analyse.",
    supervisorAgreesRaiseProb: 0.6,
    hrApprovesFireProb: 0.09,
    abmahnungLoggedProb: 0.93,
  },
  {
    id: 141,
    name: "Karl Roth",
    jobTitle: "Senior System Engineer",
    department: "IT-Infrastruktur",
    yearsInCompany: 12,
    performanceScore: 4.0,
    lastReviewSummary:
      "Tiefgreifendes technisches Wissen, zuverlässige Systemwartung.",
    scenario: "Planung der Nachfolge/Wissenstransfer.",
    supervisorAgreesRaiseProb: 0.5,
    hrApprovesFireProb: 0.1,
    abmahnungLoggedProb: 0.9,
  },
  {
    id: 142,
    name: "Marlene Winkler",
    jobTitle: "HR Managerin",
    department: "Personalwesen",
    yearsInCompany: 8,
    performanceScore: 4.7,
    lastReviewSummary:
      "Strategische Weiterentwicklung der HR-Abteilung, hohe Mitarbeiterzufriedenheit.",
    scenario: "Einführung eines neuen Leistungsbeurteilungssystems.",
    supervisorAgreesRaiseProb: 0.75,
    hrApprovesFireProb: 0.05,
    abmahnungLoggedProb: 0.98,
  },
  {
    id: 143,
    name: "Oskar Schuster",
    jobTitle: "Full-Stack Entwickler",
    department: "Technologie",
    yearsInCompany: 4,
    performanceScore: 4.1,
    lastReviewSummary:
      "Flexibel einsetzbar in Front- und Backend, liefert solide Ergebnisse.",
    scenario: "Standardmäßiger Leistungsbeurteilungszyklus.",
    supervisorAgreesRaiseProb: 0.55,
    hrApprovesFireProb: 0.1,
    abmahnungLoggedProb: 0.9,
  },
  {
    id: 144,
    name: "Lotte Lorenz",
    jobTitle: "Event Managerin",
    department: "Marketing",
    yearsInCompany: 2,
    performanceScore: 3.9,
    lastReviewSummary:
      "Erfolgreiche Organisation von Kunden-Webinaren, gutes Budgetmanagement.",
    scenario: "Planung der nächsten Messebeteiligung.",
    supervisorAgreesRaiseProb: 0.45,
    hrApprovesFireProb: 0.12,
    abmahnungLoggedProb: 0.88,
  },
  {
    id: 145,
    name: "Arthur Baumann",
    jobTitle: "Datenbankadministrator",
    department: "IT-Infrastruktur",
    yearsInCompany: 7,
    performanceScore: 4.3,
    lastReviewSummary:
      "Sicherstellung der Datenbankintegrität und -performance, schnelle Problembehebung.",
    scenario: "Evaluierung neuer Datenbanktechnologien.",
    supervisorAgreesRaiseProb: 0.6,
    hrApprovesFireProb: 0.09,
    abmahnungLoggedProb: 0.92,
  },
  {
    id: 146,
    name: "Mathilda Albrecht",
    jobTitle: "Business Analystin",
    department: "Business Intelligence",
    yearsInCompany: 5,
    performanceScore: 4.5,
    lastReviewSummary:
      "Exzellente Anforderungsanalyse, Brücke zwischen Fachbereich und IT.",
    scenario: "Leitung eines Workshops zur Prozessoptimierung.",
    supervisorAgreesRaiseProb: 0.7,
    hrApprovesFireProb: 0.07,
    abmahnungLoggedProb: 0.95,
  },
  {
    id: 147,
    name: "Bruno Simon",
    jobTitle: "Auszubildender Fachinformatiker Systemintegration",
    department: "IT-Infrastruktur",
    yearsInCompany: 1,
    performanceScore: 3.4,
    lastReviewSummary:
      "Zeigt großes Interesse und lernt schnell, benötigt noch Anleitung.",
    scenario: "Zwischenprüfungsvorbereitung.",
    supervisorAgreesRaiseProb: 0.2,
    hrApprovesFireProb: 0.18,
    abmahnungLoggedProb: 0.89,
  },
  {
    id: 148,
    name: "Helena Seidel",
    jobTitle: "PR Managerin",
    department: "Marketing",
    yearsInCompany: 6,
    performanceScore: 4.2,
    lastReviewSummary:
      "Gute Medienpräsenz aufgebaut, positive Berichterstattung gesichert.",
    scenario: "Krisenkommunikationsplan entwickeln.",
    supervisorAgreesRaiseProb: 0.6,
    hrApprovesFireProb: 0.1,
    abmahnungLoggedProb: 0.91,
  },
  {
    id: 149,
    name: "Vincent Keller",
    jobTitle: "Software Architekt",
    department: "Technologie",
    yearsInCompany: 10,
    performanceScore: 4.9,
    lastReviewSummary:
      "Entwicklung zukunftsweisender Softwarearchitekturen, technischer Visionär.",
    scenario: "Strategische Technologieentscheidungen für neue Produktlinie.",
    supervisorAgreesRaiseProb: 0.85,
    hrApprovesFireProb: 0.03,
    abmahnungLoggedProb: 0.99,
  },
  {
    id: 150,
    name: "Romy Horn",
    jobTitle: "Lohnbuchhalterin",
    department: "Personalwesen",
    yearsInCompany: 4,
    performanceScore: 3.9,
    lastReviewSummary:
      "Korrekte und pünktliche Gehaltsabrechnung, aber manchmal schwer erreichbar.",
    scenario: "Standardmäßiger Leistungsbeurteilungszyklus.",
    supervisorAgreesRaiseProb: 0.45,
    hrApprovesFireProb: 0.11,
    abmahnungLoggedProb: 0.88,
  },
  {
    id: 151,
    name: "Jonathan Fink",
    jobTitle: "IT-Einkäufer",
    department: "Einkauf",
    yearsInCompany: 5,
    performanceScore: 4.0,
    lastReviewSummary:
      "Gute Verhandlungsergebnisse bei Hardware- und Softwarebeschaffung.",
    scenario: "Rahmenvertragsverhandlungen mit neuem Lieferanten.",
    supervisorAgreesRaiseProb: 0.5,
    hrApprovesFireProb: 0.1,
    abmahnungLoggedProb: 0.9,
  },
  {
    id: 152,
    name: "Valerie Brandt",
    jobTitle: "UX Researcher",
    department: "Design",
    yearsInCompany: 3,
    performanceScore: 4.4,
    lastReviewSummary:
      "Liefert wertvolle Einblicke in Nutzerverhalten durch Usability-Tests.",
    scenario: "Planung von Nutzerinterviews für neues Feature.",
    supervisorAgreesRaiseProb: 0.65,
    hrApprovesFireProb: 0.08,
    abmahnungLoggedProb: 0.94,
  },
  {
    id: 153,
    name: "Ludwig Jäger",
    jobTitle: "Technischer Support (2nd Level)",
    department: "Support",
    yearsInCompany: 4,
    performanceScore: 3.7,
    lastReviewSummary:
      "Löst komplexe technische Probleme, aber Dokumentation der Lösungen könnte besser sein.",
    scenario: "Schulung zu Wissensdatenbank-Management.",
    supervisorAgreesRaiseProb: 0.35,
    hrApprovesFireProb: 0.15,
    abmahnungLoggedProb: 0.85,
  },
  {
    id: 154,
    name: "Annelie Pohl",
    jobTitle: "Marketingassistenz",
    department: "Marketing",
    yearsInCompany: 1,
    performanceScore: 3.6,
    lastReviewSummary:
      "Unterstützt das Team zuverlässig bei organisatorischen Aufgaben.",
    scenario: "Erstes Jahresgespräch.",
    supervisorAgreesRaiseProb: 0.3,
    hrApprovesFireProb: 0.16,
    abmahnungLoggedProb: 0.87,
  },
  {
    id: 155,
    name: "Konrad Werner",
    jobTitle: "Leiter Qualitätssicherung",
    department: "Qualitätssicherung",
    yearsInCompany: 8,
    performanceScore: 4.5,
    lastReviewSummary:
      "Implementierung effektiver Testprozesse, Reduzierung von Bugs in Releases.",
    scenario: "Budgetplanung für Testautomatisierungstools.",
    supervisorAgreesRaiseProb: 0.7,
    hrApprovesFireProb: 0.07,
    abmahnungLoggedProb: 0.95,
  },
  {
    id: 156,
    name: "Antonia Kurz",
    jobTitle: "Personalentwicklerin",
    department: "Personalwesen",
    yearsInCompany: 5,
    performanceScore: 4.3,
    lastReviewSummary:
      "Entwicklung und Durchführung erfolgreicher Schulungsprogramme.",
    scenario: "Konzeption eines Führungskräfteentwicklungsprogramms.",
    supervisorAgreesRaiseProb: 0.6,
    hrApprovesFireProb: 0.09,
    abmahnungLoggedProb: 0.93,
  },
  {
    id: 157,
    name: "Hannes Kramer",
    jobTitle: "Junior Systemadministrator",
    department: "IT-Infrastruktur",
    yearsInCompany: 1,
    performanceScore: 3.1,
    lastReviewSummary:
      "Erledigt zugewiesene Aufgaben, benötigt mehr Selbstständigkeit.",
    scenario: "Fehler bei Serverkonfiguration (geringfügig).",
    supervisorAgreesRaiseProb: 0.15,
    hrApprovesFireProb: 0.25,
    abmahnungLoggedProb: 0.8,
  },
  {
    id: 158,
    name: "Franziska Haas",
    jobTitle: "Sales Managerin B2B",
    department: "Vertrieb",
    yearsInCompany: 6,
    performanceScore: 4.8,
    lastReviewSummary:
      "Übertrifft konstant die Umsatzziele, exzellente Kundenbindung.",
    scenario: "Verhandlung eines großen Rahmenvertrags.",
    supervisorAgreesRaiseProb: 0.8,
    hrApprovesFireProb: 0.05,
    abmahnungLoggedProb: 0.98,
  },
  {
    id: 159,
    name: "Richard Voigt",
    jobTitle: "IT-Projektkoordinator",
    department: "Projektmanagement",
    yearsInCompany: 3,
    performanceScore: 3.8,
    lastReviewSummary:
      "Unterstützt Projektmanager effektiv, gute organisatorische Fähigkeiten.",
    scenario: "Übernahme erster kleinerer Teilprojekte.",
    supervisorAgreesRaiseProb: 0.4,
    hrApprovesFireProb: 0.13,
    abmahnungLoggedProb: 0.87,
  },
  {
    id: 160,
    name: "Margarete Stein",
    jobTitle: "Senior Buchhalterin",
    department: "Finanzen",
    yearsInCompany: 15,
    performanceScore: 4.2,
    lastReviewSummary:
      "Umfassendes Wissen in Buchhaltung und Steuern, sehr zuverlässig.",
    scenario: "Vorbereitung auf externe Wirtschaftsprüfung.",
    supervisorAgreesRaiseProb: 0.6,
    hrApprovesFireProb: 0.08,
    abmahnungLoggedProb: 0.92,
  },
  {
    id: 161,
    name: "Stefan Pfeiffer",
    jobTitle: "Data Scientist",
    department: "Business Intelligence",
    yearsInCompany: 4,
    performanceScore: 4.6,
    lastReviewSummary:
      "Entwicklung prädiktiver Modelle mit hohem Geschäftswert.",
    scenario: "Präsentation der Analyseergebnisse vor dem Management.",
    supervisorAgreesRaiseProb: 0.7,
    hrApprovesFireProb: 0.06,
    abmahnungLoggedProb: 0.96,
  },
  {
    id: 162,
    name: "Heidi Otto",
    jobTitle: "Empfangsmitarbeiterin",
    department: "Verwaltung",
    yearsInCompany: 2,
    performanceScore: 3.5,
    lastReviewSummary:
      "Freundlicher erster Kontakt für Besucher, aber manchmal Probleme bei der Aufgabenpriorisierung.",
    scenario: "Diskussion über Zeitmanagement.",
    supervisorAgreesRaiseProb: 0.25,
    hrApprovesFireProb: 0.18,
    abmahnungLoggedProb: 0.84,
  },
  {
    id: 163,
    name: "Georg Engel",
    jobTitle: "Mobile App Entwickler (Android)",
    department: "Technologie",
    yearsInCompany: 3,
    performanceScore: 4.0,
    lastReviewSummary:
      "Solide Entwicklung für Android-Plattform, gute Teamarbeit.",
    scenario: "Standardmäßiger Leistungsbeurteilungszyklus.",
    supervisorAgreesRaiseProb: 0.5,
    hrApprovesFireProb: 0.1,
    abmahnungLoggedProb: 0.9,
  },
  {
    id: 164,
    name: "Isabelle Sauer",
    jobTitle: "Legal Assistant",
    department: "Recht",
    yearsInCompany: 4,
    performanceScore: 4.1,
    lastReviewSummary:
      "Effiziente Unterstützung der Rechtsabteilung, sorgfältige Aktenführung.",
    scenario: "Unterstützung bei Due-Diligence-Prüfung.",
    supervisorAgreesRaiseProb: 0.55,
    hrApprovesFireProb: 0.1,
    abmahnungLoggedProb: 0.91,
  },
  {
    id: 165,
    name: "Manfred Kern",
    jobTitle: "Facility Manager",
    department: "Verwaltung",
    yearsInCompany: 9,
    performanceScore: 3.9,
    lastReviewSummary:
      "Sicherstellung der Gebäudefunktionalität, aber Budgetüberschreitungen bei Reparaturen.",
    scenario: "Diskussion über Kostenkontrolle im Facility Management.",
    supervisorAgreesRaiseProb: 0.4,
    hrApprovesFireProb: 0.14,
    abmahnungLoggedProb: 0.86,
  },
  {
    id: 166,
    name: "Ulrike Sommer",
    jobTitle: "Chief Technology Officer (CTO)",
    department: "Management",
    yearsInCompany: 7,
    performanceScore: 4.9,
    lastReviewSummary:
      "Strategische Führung der Technologieabteilung, Förderung von Innovation.",
    scenario: "Präsentation der Technologiestrategie vor dem Vorstand.",
    supervisorAgreesRaiseProb: 0.9,
    hrApprovesFireProb: 0.02,
    abmahnungLoggedProb: 0.99,
  },
  {
    id: 167,
    name: "Robert Busch",
    jobTitle: "IT-Trainer",
    department: "Personalwesen",
    yearsInCompany: 5,
    performanceScore: 4.2,
    lastReviewSummary:
      "Durchführung effektiver Schulungen zu interner Software, positives Feedback.",
    scenario: "Entwicklung eines neuen E-Learning-Moduls.",
    supervisorAgreesRaiseProb: 0.6,
    hrApprovesFireProb: 0.1,
    abmahnungLoggedProb: 0.91,
  },
  {
    id: 168,
    name: "Sabine Arnold",
    jobTitle: "Testautomatisierer",
    department: "Qualitätssicherung",
    yearsInCompany: 3,
    performanceScore: 4.4,
    lastReviewSummary:
      "Aufbau und Wartung robuster Testautomatisierungs-Frameworks.",
    scenario: "Evaluierung neuer Automatisierungstools.",
    supervisorAgreesRaiseProb: 0.65,
    hrApprovesFireProb: 0.08,
    abmahnungLoggedProb: 0.94,
  },
  {
    id: 169,
    name: "Michael Wolff",
    jobTitle: "Chief Financial Officer (CFO)",
    department: "Management",
    yearsInCompany: 10,
    performanceScore: 4.7,
    lastReviewSummary:
      "Solide Finanzplanung und -steuerung, erfolgreiche Finanzierungsrunden.",
    scenario:
      "Jahresabschluss und Budgetplanung für das nächste Geschäftsjahr.",
    supervisorAgreesRaiseProb: 0.85,
    hrApprovesFireProb: 0.04,
    abmahnungLoggedProb: 0.98,
  },
  {
    id: 170,
    name: "Daniela Kuhn",
    jobTitle: "IT-Compliance Beauftragte",
    department: "IT-Sicherheit",
    yearsInCompany: 6,
    performanceScore: 4.5,
    lastReviewSummary:
      "Sicherstellung der Einhaltung relevanter IT-Standards und Vorschriften.",
    scenario: "Vorbereitung auf ISO 27001 Audit.",
    supervisorAgreesRaiseProb: 0.7,
    hrApprovesFireProb: 0.07,
    abmahnungLoggedProb: 0.96,
  },
  {
    id: 171,
    name: "Christian Ziegler",
    jobTitle: "Leiter Marketing",
    department: "Marketing",
    yearsInCompany: 8,
    performanceScore: 4.6,
    lastReviewSummary:
      "Erfolgreiche Markenpositionierung, starkes Wachstum der Marketing-KPIs.",
    scenario: "Entwicklung der Marketingstrategie für neues Produkt.",
    supervisorAgreesRaiseProb: 0.75,
    hrApprovesFireProb: 0.06,
    abmahnungLoggedProb: 0.97,
  },
  {
    id: 172,
    name: "Sandra Kraft",
    jobTitle: "Assistenz der Geschäftsführung",
    department: "Management",
    yearsInCompany: 5,
    performanceScore: 4.8,
    lastReviewSummary:
      "Exzellente organisatorische Unterstützung, hohe Vertrauenswürdigkeit und Diskretion.",
    scenario: "Organisation einer wichtigen Vorstandssitzung.",
    supervisorAgreesRaiseProb: 0.8,
    hrApprovesFireProb: 0.05,
    abmahnungLoggedProb: 0.99,
  },
  {
    id: 173,
    name: "Andreas Keller",
    jobTitle: "Softwareentwickler (Praktikant)",
    department: "Technologie",
    yearsInCompany: 0.5,
    performanceScore: 3.0,
    lastReviewSummary:
      "Zeigt Potenzial, erledigt einfache Programmieraufgaben.",
    scenario: "Abschlussgespräch Praktikum, mögliche Übernahme als Junior.",
    supervisorAgreesRaiseProb: 0.3,
    hrApprovesFireProb: 0.2,
    abmahnungLoggedProb: 0.9,
  },
  {
    id: 174,
    name: "Nicole Grimm",
    jobTitle: "Leiterin Personalwesen",
    department: "Personalwesen",
    yearsInCompany: 9,
    performanceScore: 4.7,
    lastReviewSummary:
      "Aufbau einer starken HR-Struktur, positive Unternehmenskultur gefördert.",
    scenario: "Strategische Personalplanung.",
    supervisorAgreesRaiseProb: 0.8,
    hrApprovesFireProb: 0.05,
    abmahnungLoggedProb: 0.98,
  },
  {
    id: 175,
    name: "Markus Hess",
    jobTitle: "Netzwerkspezialist",
    department: "IT-Infrastruktur",
    yearsInCompany: 6,
    performanceScore: 4.1,
    lastReviewSummary:
      "Expertise in komplexen Netzwerkumgebungen, gute Problemlösung.",
    scenario: "Planung einer Netzwerksegmentierung.",
    supervisorAgreesRaiseProb: 0.55,
    hrApprovesFireProb: 0.1,
    abmahnungLoggedProb: 0.9,
  },
  {
    id: 176,
    name: "Julia Ernst",
    jobTitle: "Chief Operating Officer (COO)",
    department: "Management",
    yearsInCompany: 6,
    performanceScore: 4.8,
    lastReviewSummary:
      "Optimierung interner Prozesse, Steigerung der operativen Effizienz.",
    scenario: "Implementierung neuer Workflow-Management-Software.",
    supervisorAgreesRaiseProb: 0.85,
    hrApprovesFireProb: 0.04,
    abmahnungLoggedProb: 0.99,
  },
  {
    id: 177,
    name: "Tobias Meier",
    jobTitle: "Softwareentwickler",
    department: "Technologie",
    yearsInCompany: 5,
    performanceScore: 4.3,
    lastReviewSummary:
      "Zuverlässiger Entwickler, liefert konstant gute Arbeit ab.",
    scenario: "Standardmäßiger Leistungsbeurteilungszyklus.",
    supervisorAgreesRaiseProb: 0.6,
    hrApprovesFireProb: 0.09,
    abmahnungLoggedProb: 0.94,
  },
  {
    id: 178,
    name: "Laura Kurz",
    jobTitle: "Junior Softwareentwicklerin",
    department: "Technologie",
    yearsInCompany: 1.5,
    performanceScore: 3.7,
    lastReviewSummary:
      "Gute Fortschritte im ersten Jahr, übernimmt mehr Verantwortung.",
    scenario: "Diskussion über Weiterbildungsmöglichkeiten.",
    supervisorAgreesRaiseProb: 0.4,
    hrApprovesFireProb: 0.12,
    abmahnungLoggedProb: 0.9,
  },
  {
    id: 179,
    name: "Florian Graf",
    jobTitle: "Senior Software Engineer",
    department: "Technologie",
    yearsInCompany: 8,
    performanceScore: 4.7,
    lastReviewSummary:
      "Technischer Lead in Projekt Y, exzellentes Mentoring für Juniors.",
    scenario: "Antrag auf Teilnahme an internationaler Konferenz.",
    supervisorAgreesRaiseProb: 0.75,
    hrApprovesFireProb: 0.05,
    abmahnungLoggedProb: 0.98,
  },
  {
    id: 180,
    name: "Melanie Braun",
    jobTitle: "Systemadministratorin",
    department: "IT-Infrastruktur",
    yearsInCompany: 3,
    performanceScore: 3.8,
    lastReviewSummary:
      "Reagiert schnell auf Incidents, Verbesserung bei proaktiver Planung möglich.",
    scenario: "Standardmäßiger Leistungsbeurteilungszyklus.",
    supervisorAgreesRaiseProb: 0.4,
    hrApprovesFireProb: 0.13,
    abmahnungLoggedProb: 0.87,
  },
  {
    id: 181,
    name: "Dennis Krause",
    jobTitle: "IT-Support Spezialist",
    department: "Support",
    yearsInCompany: 2,
    performanceScore: 3.4,
    lastReviewSummary:
      "Freundlich im Umgang mit Usern, Ticketlösungszeiten durchschnittlich.",
    scenario: "Teilnahme an Kundenservice-Schulung.",
    supervisorAgreesRaiseProb: 0.25,
    hrApprovesFireProb: 0.18,
    abmahnungLoggedProb: 0.85,
  },
  {
    id: 182,
    name: "Sarah Petersen",
    jobTitle: "IT-Support Spezialistin",
    department: "Support",
    yearsInCompany: 4,
    performanceScore: 4.0,
    lastReviewSummary:
      "Hohe Lösungsquote bei First-Level-Tickets, gute Dokumentation.",
    scenario: "Übernahme von Verantwortung für Wissensdatenbank.",
    supervisorAgreesRaiseProb: 0.5,
    hrApprovesFireProb: 0.1,
    abmahnungLoggedProb: 0.9,
  },
  {
    id: 183,
    name: "Alexander Beck",
    jobTitle: "Projektmanager",
    department: "Projektmanagement",
    yearsInCompany: 5,
    performanceScore: 4.1,
    lastReviewSummary:
      "Managt Projekte zuverlässig nach Plan, könnte Risikomanagement verbessern.",
    scenario: "Standardmäßiger Leistungsbeurteilungszyklus.",
    supervisorAgreesRaiseProb: 0.55,
    hrApprovesFireProb: 0.1,
    abmahnungLoggedProb: 0.91,
  },
  {
    id: 184,
    name: "Katharina Horn",
    jobTitle: "Junior Projektmanagerin",
    department: "Projektmanagement",
    yearsInCompany: 2,
    performanceScore: 3.9,
    lastReviewSummary:
      "Unterstützt Senior PMs gut, lernt schnell Projektmethodiken.",
    scenario: "Erste eigenverantwortliche Leitung kleinerer Projekte.",
    supervisorAgreesRaiseProb: 0.45,
    hrApprovesFireProb: 0.11,
    abmahnungLoggedProb: 0.89,
  },
  {
    id: 185,
    name: "Steffen Ludwig",
    jobTitle: "Vertriebsmitarbeiter",
    department: "Vertrieb",
    yearsInCompany: 3,
    performanceScore: 3.6,
    lastReviewSummary:
      "Erreicht Ziele meist, benötigt mehr Initiative bei Kaltakquise.",
    scenario: "Diskussion über Vertriebsziele Q3.",
    supervisorAgreesRaiseProb: 0.3,
    hrApprovesFireProb: 0.16,
    abmahnungLoggedProb: 0.84,
  },
  {
    id: 186,
    name: "Christina Böhm",
    jobTitle: "Key Account Managerin",
    department: "Vertrieb",
    yearsInCompany: 7,
    performanceScore: 4.5,
    lastReviewSummary:
      "Exzellente Betreuung von Großkunden, hohe Kundenzufriedenheit.",
    scenario: "Verlängerung eines wichtigen Kundenvertrags.",
    supervisorAgreesRaiseProb: 0.7,
    hrApprovesFireProb: 0.07,
    abmahnungLoggedProb: 0.96,
  },
  {
    id: 187,
    name: "Martin Engelhardt",
    jobTitle: "Recruiter",
    department: "Personalwesen",
    yearsInCompany: 4,
    performanceScore: 4.0,
    lastReviewSummary:
      "Gutes Netzwerk, findet passende Kandidaten für technische Rollen.",
    scenario: "Planung einer Recruiting-Kampagne für Entwickler.",
    supervisorAgreesRaiseProb: 0.5,
    hrApprovesFireProb: 0.1,
    abmahnungLoggedProb: 0.9,
  },
  {
    id: 188,
    name: "Vanessa Schreiber",
    jobTitle: "Personalreferentin",
    department: "Personalwesen",
    yearsInCompany: 6,
    performanceScore: 4.2,
    lastReviewSummary:
      "Kompetente Ansprechpartnerin für Mitarbeiter, gute Kenntnisse im Arbeitsrecht.",
    scenario: "Überarbeitung der Personalrichtlinien.",
    supervisorAgreesRaiseProb: 0.6,
    hrApprovesFireProb: 0.09,
    abmahnungLoggedProb: 0.92,
  },
  {
    id: 189,
    name: "Ralf Günther",
    jobTitle: "Buchhalter",
    department: "Finanzen",
    yearsInCompany: 8,
    performanceScore: 3.9,
    lastReviewSummary:
      "Erledigt Kreditorenbuchhaltung zuverlässig, manchmal langsam bei Ad-hoc-Anfragen.",
    scenario: "Standardmäßiger Leistungsbeurteilungszyklus.",
    supervisorAgreesRaiseProb: 0.45,
    hrApprovesFireProb: 0.12,
    abmahnungLoggedProb: 0.88,
  },
  {
    id: 190,
    name: "Simone Keller",
    jobTitle: "UI/UX Designerin",
    department: "Design",
    yearsInCompany: 2,
    performanceScore: 3.8,
    lastReviewSummary:
      "Kreative Ideen, benötigt mehr Erfahrung in der Umsetzung komplexer User Flows.",
    scenario: "Teilnahme an Workshop zu Interaction Design.",
    supervisorAgreesRaiseProb: 0.4,
    hrApprovesFireProb: 0.14,
    abmahnungLoggedProb: 0.86,
  },
  {
    id: 191,
    name: "Patrick Lang",
    jobTitle: "Qualitätssicherungsingenieur",
    department: "Qualitätssicherung",
    yearsInCompany: 3,
    performanceScore: 3.7,
    lastReviewSummary:
      "Identifiziert Bugs zuverlässig, Testfalldokumentation könnte detaillierter sein.",
    scenario: "Schulung zu Testfall-Design.",
    supervisorAgreesRaiseProb: 0.35,
    hrApprovesFireProb: 0.15,
    abmahnungLoggedProb: 0.85,
  },
  {
    id: 192,
    name: "Kerstin Berger",
    jobTitle: "Full-Stack Entwicklerin",
    department: "Technologie",
    yearsInCompany: 6,
    performanceScore: 4.4,
    lastReviewSummary:
      "Starke technische Fähigkeiten in Front- und Backend, sehr selbstständig.",
    scenario: "Übernahme technischer Verantwortung für ein Modul.",
    supervisorAgreesRaiseProb: 0.65,
    hrApprovesFireProb: 0.08,
    abmahnungLoggedProb: 0.95,
  },
  {
    id: 193,
    name: "Dirk Neumann",
    jobTitle: "DevOps Engineer",
    department: "Technologie",
    yearsInCompany: 2,
    performanceScore: 4.0,
    lastReviewSummary:
      "Unterstützt gut bei CI/CD-Prozessen, lernt schnell neue Tools.",
    scenario: "Standardmäßiger Leistungsbeurteilungszyklus.",
    supervisorAgreesRaiseProb: 0.5,
    hrApprovesFireProb: 0.1,
    abmahnungLoggedProb: 0.9,
  },
  {
    id: 194,
    name: "Susanne Hahn",
    jobTitle: "Datenanalystin",
    department: "Business Intelligence",
    yearsInCompany: 4,
    performanceScore: 4.2,
    lastReviewSummary:
      "Erstellt aufschlussreiche Dashboards, gute Präsentationsfähigkeiten.",
    scenario: "Analyse von Kundendaten zur Churn Prevention.",
    supervisorAgreesRaiseProb: 0.6,
    hrApprovesFireProb: 0.1,
    abmahnungLoggedProb: 0.91,
  },
  {
    id: 195,
    name: "Uwe Friedrich",
    jobTitle: "Backend-Entwickler",
    department: "Technologie",
    yearsInCompany: 7,
    performanceScore: 4.0,
    lastReviewSummary:
      "Erfahrener Entwickler, aber manchmal resistent gegenüber neuen Technologien.",
    scenario: "Diskussion über Einführung neuer Frameworks.",
    supervisorAgreesRaiseProb: 0.45,
    hrApprovesFireProb: 0.11,
    abmahnungLoggedProb: 0.88,
  },
  {
    id: 196,
    name: "Birgit Junker",
    jobTitle: "Teamassistenz",
    department: "Vertrieb",
    yearsInCompany: 5,
    performanceScore: 4.1,
    lastReviewSummary:
      "Sehr gute Unterstützung des Vertriebsteams, exzellente Organisation.",
    scenario: "Standardmäßiger Leistungsbeurteilungszyklus.",
    supervisorAgreesRaiseProb: 0.55,
    hrApprovesFireProb: 0.1,
    abmahnungLoggedProb: 0.9,
  },
  {
    id: 197,
    name: "Jürgen Schröder",
    jobTitle: "Senior Systemadministrator",
    department: "IT-Infrastruktur",
    yearsInCompany: 11,
    performanceScore: 4.5,
    lastReviewSummary:
      "Hohe Expertise in Server- und Netzwerkmanagement, löst komplexe Probleme.",
    scenario: "Mentoring für Junior-Administratoren.",
    supervisorAgreesRaiseProb: 0.7,
    hrApprovesFireProb: 0.07,
    abmahnungLoggedProb: 0.96,
  },
  {
    id: 198,
    name: "Petra Dietrich",
    jobTitle: "Frontend-Entwicklerin",
    department: "Technologie",
    yearsInCompany: 4,
    performanceScore: 4.3,
    lastReviewSummary:
      "Setzt Designs pixelgenau um, achtet auf Barrierefreiheit.",
    scenario: "Leitung eines internen Workshops zu Accessibility.",
    supervisorAgreesRaiseProb: 0.6,
    hrApprovesFireProb: 0.09,
    abmahnungLoggedProb: 0.93,
  },
  {
    id: 199,
    name: "Frank Schubert",
    jobTitle: "IT-Sicherheitsbeauftragter",
    department: "IT-Sicherheit",
    yearsInCompany: 8,
    performanceScore: 4.6,
    lastReviewSummary:
      "Implementierung und Überwachung von Sicherheitsrichtlinien, erfolgreiche Audits.",
    scenario: "Durchführung von Sicherheitsschulungen für Mitarbeiter.",
    supervisorAgreesRaiseProb: 0.7,
    hrApprovesFireProb: 0.06,
    abmahnungLoggedProb: 0.97,
  },
  {
    id: 200,
    name: "Monika Fischer",
    jobTitle: "Marketing Managerin",
    department: "Marketing",
    yearsInCompany: 5,
    performanceScore: 4.0,
    lastReviewSummary:
      "Plant und steuert Kampagnen erfolgreich, Budgeteinhaltung gut.",
    scenario: "Analyse der letzten Kampagnenergebnisse.",
    supervisorAgreesRaiseProb: 0.5,
    hrApprovesFireProb: 0.1,
    abmahnungLoggedProb: 0.9,
  },
  {
    id: 201,
    name: "Gerhard Scholz",
    jobTitle: "Softwareentwickler",
    department: "Technologie",
    yearsInCompany: 3,
    performanceScore: 3.8,
    lastReviewSummary:
      "Solide Codequalität, könnte proaktiver in Teammeetings sein.",
    scenario: "Standardmäßiger Leistungsbeurteilungszyklus.",
    supervisorAgreesRaiseProb: 0.4,
    hrApprovesFireProb: 0.13,
    abmahnungLoggedProb: 0.89,
  },
  {
    id: 202,
    name: "Silke Wagner",
    jobTitle: "Softwareentwicklerin",
    department: "Technologie",
    yearsInCompany: 6,
    performanceScore: 4.1,
    lastReviewSummary:
      "Erfahren in mehreren Programmiersprachen, gute Problemlöserin.",
    scenario: "Anfrage für Sabbatical.",
    supervisorAgreesRaiseProb: 0.5,
    hrApprovesFireProb: 0.1,
    abmahnungLoggedProb: 0.9,
  },
  {
    id: 203,
    name: "Bernd Klein",
    jobTitle: "Junior Softwareentwickler",
    department: "Technologie",
    yearsInCompany: 0.8,
    performanceScore: 3.2,
    lastReviewSummary:
      "Lernt schnell, benötigt aber noch viel Unterstützung bei komplexen Aufgaben.",
    scenario: "Erstes Feedbackgespräch nach Probezeit.",
    supervisorAgreesRaiseProb: 0.2,
    hrApprovesFireProb: 0.2,
    abmahnungLoggedProb: 0.85,
  },
  {
    id: 204,
    name: "Andrea Wolf",
    jobTitle: "Senior Software Engineer",
    department: "Technologie",
    yearsInCompany: 9,
    performanceScore: 4.5,
    lastReviewSummary:
      "Übernimmt technische Leitung in Teilprojekten, sehr zuverlässig.",
    scenario: "Diskussion über Architekturentscheidungen.",
    supervisorAgreesRaiseProb: 0.7,
    hrApprovesFireProb: 0.07,
    abmahnungLoggedProb: 0.96,
  },
  {
    id: 205,
    name: "Thomas Bauer",
    jobTitle: "Systemadministrator",
    department: "IT-Infrastruktur",
    yearsInCompany: 7,
    performanceScore: 4.0,
    lastReviewSummary:
      "Hält Systeme stabil, gute Kenntnisse in Linux-Umgebungen.",
    scenario: "Planung von Systemupdates.",
    supervisorAgreesRaiseProb: 0.5,
    hrApprovesFireProb: 0.1,
    abmahnungLoggedProb: 0.9,
  },
  {
    id: 206,
    name: "Anja Neumann",
    jobTitle: "IT-Support Spezialistin (1st Level)",
    department: "Support",
    yearsInCompany: 1,
    performanceScore: 3.6,
    lastReviewSummary:
      "Sehr kundenorientiert, lernt technische Details schnell.",
    scenario: "Erstes Jahresgespräch.",
    supervisorAgreesRaiseProb: 0.3,
    hrApprovesFireProb: 0.15,
    abmahnungLoggedProb: 0.88,
  },
  {
    id: 207,
    name: "Markus Richter",
    jobTitle: "IT-Support Spezialist (2nd Level)",
    department: "Support",
    yearsInCompany: 5,
    performanceScore: 4.2,
    lastReviewSummary: "Löst auch schwierige Fälle, unterstützt Kollegen.",
    scenario: "Vorschlag zur Verbesserung des Ticket-Systems.",
    supervisorAgreesRaiseProb: 0.6,
    hrApprovesFireProb: 0.09,
    abmahnungLoggedProb: 0.93,
  },
  {
    id: 208,
    name: "Sabrina Hoffmann",
    jobTitle: "Projektmanagerin",
    department: "Projektmanagement",
    yearsInCompany: 4,
    performanceScore: 3.9,
    lastReviewSummary:
      "Gute Projektplanung, aber manchmal Schwierigkeiten bei der Durchsetzung von Deadlines.",
    scenario: "Coaching zu Konfliktmanagement.",
    supervisorAgreesRaiseProb: 0.45,
    hrApprovesFireProb: 0.12,
    abmahnungLoggedProb: 0.87,
  },
  {
    id: 209,
    name: "Oliver Lange",
    jobTitle: "Senior Projektmanager",
    department: "Projektmanagement",
    yearsInCompany: 10,
    performanceScore: 4.7,
    lastReviewSummary:
      "Erfolgreiche Leitung komplexer, internationaler Projekte.",
    scenario: "Mentoring für Junior Projektmanager.",
    supervisorAgreesRaiseProb: 0.75,
    hrApprovesFireProb: 0.05,
    abmahnungLoggedProb: 0.98,
  },
  {
    id: 210,
    name: "Jessica Simon",
    jobTitle: "Vertriebsmitarbeiterin",
    department: "Vertrieb",
    yearsInCompany: 2,
    performanceScore: 4.0,
    lastReviewSummary: "Sehr engagiert, baut gute Kundenbeziehungen auf.",
    scenario: "Standardmäßiger Leistungsbeurteilungszyklus.",
    supervisorAgreesRaiseProb: 0.5,
    hrApprovesFireProb: 0.1,
    abmahnungLoggedProb: 0.9,
  },
  {
    id: 211,
    name: "Mario Vogel",
    jobTitle: "Vertriebsmitarbeiter (Innendienst)",
    department: "Vertrieb",
    yearsInCompany: 6,
    performanceScore: 3.8,
    lastReviewSummary:
      "Unterstützt Außendienst zuverlässig, gute Angebotsverwaltung.",
    scenario: "Diskussion über Provisionsmodell Innendienst.",
    supervisorAgreesRaiseProb: 0.4,
    hrApprovesFireProb: 0.13,
    abmahnungLoggedProb: 0.88,
  },
  {
    id: 212,
    name: "Tanja Keller",
    jobTitle: "Recruiterin (Tech)",
    department: "Personalwesen",
    yearsInCompany: 3,
    performanceScore: 4.3,
    lastReviewSummary:
      "Erfolgreiche Besetzung schwieriger Tech-Positionen, gutes Kandidatenmanagement.",
    scenario: "Teilnahme an IT-Recruiting Messe.",
    supervisorAgreesRaiseProb: 0.6,
    hrApprovesFireProb: 0.08,
    abmahnungLoggedProb: 0.94,
  },
  {
    id: 213,
    name: "Harald Berg",
    jobTitle: "Personalreferent (Administration)",
    department: "Personalwesen",
    yearsInCompany: 7,
    performanceScore: 4.0,
    lastReviewSummary: "Effiziente Verwaltung von Personalakten und Verträgen.",
    scenario: "Einführung einer digitalen Personalakte.",
    supervisorAgreesRaiseProb: 0.5,
    hrApprovesFireProb: 0.1,
    abmahnungLoggedProb: 0.9,
  },
  {
    id: 214,
    name: "Elena Bergmann",
    jobTitle: "Buchhalterin (Debitoren)",
    department: "Finanzen",
    yearsInCompany: 5,
    performanceScore: 4.1,
    lastReviewSummary:
      "Sorgt für pünktliche Zahlungseingänge, gutes Mahnwesen.",
    scenario: "Standardmäßiger Leistungsbeurteilungszyklus.",
    supervisorAgreesRaiseProb: 0.55,
    hrApprovesFireProb: 0.1,
    abmahnungLoggedProb: 0.91,
  },
  {
    id: 215,
    name: "Axel Franke",
    jobTitle: "Qualitätssicherungsingenieur (Manuell)",
    department: "Qualitätssicherung",
    yearsInCompany: 4,
    performanceScore: 3.5,
    lastReviewSummary:
      "Findet zuverlässig funktionale Fehler, könnte Testfälle präziser beschreiben.",
    scenario: "Diskussion über Testmethodiken.",
    supervisorAgreesRaiseProb: 0.25,
    hrApprovesFireProb: 0.18,
    abmahnungLoggedProb: 0.83,
  },
  {
    id: 216,
    name: "Claudia Roth",
    jobTitle: "Testautomatisiererin",
    department: "Qualitätssicherung",
    yearsInCompany: 2,
    performanceScore: 4.0,
    lastReviewSummary:
      "Schnelle Einarbeitung in Automatisierungs-Frameworks, motiviert.",
    scenario: "Erweiterung der Testabdeckung für Modul Z.",
    supervisorAgreesRaiseProb: 0.5,
    hrApprovesFireProb: 0.11,
    abmahnungLoggedProb: 0.9,
  },
  {
    id: 217,
    name: "Werner Winkler",
    jobTitle: "Full-Stack Entwickler",
    department: "Technologie",
    yearsInCompany: 8,
    performanceScore: 4.2,
    lastReviewSummary:
      "Sehr erfahren, kann komplexe Features eigenständig umsetzen.",
    scenario: "Technische Klärung mit externem Dienstleister.",
    supervisorAgreesRaiseProb: 0.6,
    hrApprovesFireProb: 0.09,
    abmahnungLoggedProb: 0.92,
  },
  {
    id: 218,
    name: "Ursula Schuster",
    jobTitle: "Frontend-Entwicklerin",
    department: "Technologie",
    yearsInCompany: 2,
    performanceScore: 3.7,
    lastReviewSummary:
      "Gutes Auge für Design-Details, lernt schnell neue JS-Frameworks.",
    scenario: "Standardmäßiger Leistungsbeurteilungszyklus.",
    supervisorAgreesRaiseProb: 0.35,
    hrApprovesFireProb: 0.14,
    abmahnungLoggedProb: 0.87,
  },
  {
    id: 219,
    name: "Holger Lorenz",
    jobTitle: "Backend-Entwickler",
    department: "Technologie",
    yearsInCompany: 5,
    performanceScore: 4.3,
    lastReviewSummary: "Entwickelt performante und sichere Backend-Services.",
    scenario: "Optimierung einer Datenbankabfrage.",
    supervisorAgreesRaiseProb: 0.6,
    hrApprovesFireProb: 0.08,
    abmahnungLoggedProb: 0.94,
  },
  {
    id: 220,
    name: "Beate Baumann",
    jobTitle: "Teamassistenz",
    department: "Marketing",
    yearsInCompany: 4,
    performanceScore: 4.0,
    lastReviewSummary:
      "Organisiert Meetings und Reisen effizient, unterstützt bei Kampagnen.",
    scenario: "Standardmäßiger Leistungsbeurteilungszyklus.",
    supervisorAgreesRaiseProb: 0.5,
    hrApprovesFireProb: 0.1,
    abmahnungLoggedProb: 0.9,
  },
  {
    id: 221,
    name: "Rainer Albrecht",
    jobTitle: "Datenbankentwickler",
    department: "Technologie",
    yearsInCompany: 9,
    performanceScore: 4.4,
    lastReviewSummary: "Experte für Datenbankdesign und SQL-Optimierung.",
    scenario: "Design der Datenbank für neues Produkt.",
    supervisorAgreesRaiseProb: 0.65,
    hrApprovesFireProb: 0.07,
    abmahnungLoggedProb: 0.95,
  },
  {
    id: 222,
    name: "Gisela Simon",
    jobTitle: "Performance Marketing Managerin",
    department: "Marketing",
    yearsInCompany: 3,
    performanceScore: 4.5,
    lastReviewSummary:
      "Optimiert erfolgreich Google Ads und Social Media Kampagnen, hoher ROI.",
    scenario: "Budgetplanung für Performance-Kanäle.",
    supervisorAgreesRaiseProb: 0.7,
    hrApprovesFireProb: 0.06,
    abmahnungLoggedProb: 0.97,
  },
  {
    id: 223,
    name: "Kurt Seidel",
    jobTitle: "Auszubildender Fachinformatiker Anwendungsentwicklung",
    department: "Technologie",
    yearsInCompany: 2,
    performanceScore: 3.8,
    lastReviewSummary:
      "Zeigt gute Fortschritte im zweiten Lehrjahr, übernimmt erste Teilaufgaben.",
    scenario: "Planung des nächsten Ausbildungsprojekts.",
    supervisorAgreesRaiseProb: 0.4,
    hrApprovesFireProb: 0.13,
    abmahnungLoggedProb: 0.9,
  },
  {
    id: 224,
    name: "Ingrid Horn",
    jobTitle: "Interne Kommunikation Spezialistin",
    department: "Personalwesen",
    yearsInCompany: 4,
    performanceScore: 4.2,
    lastReviewSummary:
      "Verbessert Mitarbeiterinformation durch Newsletter und Intranet.",
    scenario: "Kommunikationsplan für Organisationsänderung.",
    supervisorAgreesRaiseProb: 0.6,
    hrApprovesFireProb: 0.1,
    abmahnungLoggedProb: 0.91,
  },
  {
    id: 225,
    name: "Wolfgang Fink",
    jobTitle: "Team Lead Backend Entwicklung",
    department: "Technologie",
    yearsInCompany: 8,
    performanceScore: 4.6,
    lastReviewSummary:
      "Führt das Backend-Team erfolgreich, fördert Entwickler.",
    scenario: "Ressourcenplanung für nächstes Quartal.",
    supervisorAgreesRaiseProb: 0.75,
    hrApprovesFireProb: 0.06,
    abmahnungLoggedProb: 0.97,
  },
  {
    id: 226,
    name: "Heike Brandt",
    jobTitle: "Auszubildende Kauffrau für Büromanagement",
    department: "Verwaltung",
    yearsInCompany: 1,
    performanceScore: 3.5,
    lastReviewSummary:
      "Engagiert und zuverlässig bei administrativen Aufgaben.",
    scenario: "Rotation in die Finanzabteilung.",
    supervisorAgreesRaiseProb: 0.25,
    hrApprovesFireProb: 0.17,
    abmahnungLoggedProb: 0.88,
  },
  {
    id: 227,
    name: "Jochen Jäger",
    jobTitle: "IT-Support Spezialist",
    department: "Support",
    yearsInCompany: 6,
    performanceScore: 3.7,
    lastReviewSummary: "Erfahren, aber manchmal ungeduldig mit Anwendern.",
    scenario: "Feedbackgespräch zu Kommunikationsstil.",
    supervisorAgreesRaiseProb: 0.3,
    hrApprovesFireProb: 0.16,
    abmahnungLoggedProb: 0.82,
  },
  {
    id: 228,
    name: "Marion Pohl",
    jobTitle: "Softwareentwicklerin",
    department: "Technologie",
    yearsInCompany: 2,
    performanceScore: 3.9,
    lastReviewSummary:
      "Gute Codequalität, braucht manchmal länger für Aufgaben.",
    scenario: "Standardmäßiger Leistungsbeurteilungszyklus.",
    supervisorAgreesRaiseProb: 0.45,
    hrApprovesFireProb: 0.12,
    abmahnungLoggedProb: 0.89,
  },
  {
    id: 229,
    name: "Heinz Werner",
    jobTitle: "Senior Sales Manager",
    department: "Vertrieb",
    yearsInCompany: 12,
    performanceScore: 4.3,
    lastReviewSummary: "Sehr erfahren im Lösungsvertrieb, starkes Netzwerk.",
    scenario: "Strategische Kundenentwicklung.",
    supervisorAgreesRaiseProb: 0.65,
    hrApprovesFireProb: 0.08,
    abmahnungLoggedProb: 0.94,
  },
  {
    id: 230,
    name: "Erika Kurz",
    jobTitle: "Projektmanagerin",
    department: "Projektmanagement",
    yearsInCompany: 6,
    performanceScore: 4.4,
    lastReviewSummary:
      "Sehr strukturiert, liefert Projekte pünktlich und im Budget.",
    scenario: "Übernahme eines kritischen Kundenprojekts.",
    supervisorAgreesRaiseProb: 0.65,
    hrApprovesFireProb: 0.07,
    abmahnungLoggedProb: 0.95,
  },
  {
    id: 231,
    name: "Dieter Kramer",
    jobTitle: "System Engineer",
    department: "IT-Infrastruktur",
    yearsInCompany: 5,
    performanceScore: 4.1,
    lastReviewSummary:
      "Spezialist für Virtualisierung, zuverlässig und kompetent.",
    scenario: "Planung der Migration auf neue Virtualisierungsplattform.",
    supervisorAgreesRaiseProb: 0.55,
    hrApprovesFireProb: 0.1,
    abmahnungLoggedProb: 0.9,
  },
  {
    id: 232,
    name: "Renate Haas",
    jobTitle: "Personalreferentin (Recruiting)",
    department: "Personalwesen",
    yearsInCompany: 4,
    performanceScore: 3.8,
    lastReviewSummary:
      "Findet Kandidaten, aber Prozessdokumentation lückenhaft.",
    scenario: "Schulung zu Bewerbermanagementsystem.",
    supervisorAgreesRaiseProb: 0.4,
    hrApprovesFireProb: 0.13,
    abmahnungLoggedProb: 0.86,
  },
  {
    id: 233,
    name: "Siegfried Voigt",
    jobTitle: "Softwareentwickler",
    department: "Technologie",
    yearsInCompany: 10,
    performanceScore: 3.9,
    lastReviewSummary:
      "Sehr erfahren, aber wenig offen für Pair Programming oder neue Methoden.",
    scenario: "Diskussion über Teamkollaboration.",
    supervisorAgreesRaiseProb: 0.4,
    hrApprovesFireProb: 0.14,
    abmahnungLoggedProb: 0.85,
  },
  {
    id: 234,
    name: "Karin Stein",
    jobTitle: "Office Managerin",
    department: "Verwaltung",
    yearsInCompany: 3,
    performanceScore: 4.5,
    lastReviewSummary:
      "Organisiert das Büro perfekt, sehr proaktiv und lösungsorientiert.",
    scenario: "Optimierung der internen Bestellprozesse.",
    supervisorAgreesRaiseProb: 0.7,
    hrApprovesFireProb: 0.06,
    abmahnungLoggedProb: 0.97,
  },
  {
    id: 235,
    name: "Norbert Pfeiffer",
    jobTitle: "IT-Support Spezialist",
    department: "Support",
    yearsInCompany: 8,
    performanceScore: 3.2,
    lastReviewSummary: "Technisch versiert, aber Kundenzufriedenheit gesunken.",
    scenario: "Leistungsverbesserungsplan (PIP) gestartet.",
    supervisorAgreesRaiseProb: 0.1,
    hrApprovesFireProb: 0.4,
    abmahnungLoggedProb: 0.7,
  },
  {
    id: 236,
    name: "Michaela Otto",
    jobTitle: "Junior Marketing Managerin",
    department: "Marketing",
    yearsInCompany: 1.5,
    performanceScore: 4.0,
    lastReviewSummary:
      "Unterstützt Kampagnen gut, übernimmt erste eigene Projekte.",
    scenario: "Diskussion über Spezialisierung (z.B. Content, SEO).",
    supervisorAgreesRaiseProb: 0.5,
    hrApprovesFireProb: 0.1,
    abmahnungLoggedProb: 0.9,
  },
  {
    id: 237,
    name: "Egon Engel",
    jobTitle: "Qualitätssicherungsingenieur",
    department: "Qualitätssicherung",
    yearsInCompany: 6,
    performanceScore: 4.1,
    lastReviewSummary:
      "Entwickelt gute Teststrategien, arbeitet eng mit Entwicklern zusammen.",
    scenario: "Standardmäßiger Leistungsbeurteilungszyklus.",
    supervisorAgreesRaiseProb: 0.55,
    hrApprovesFireProb: 0.1,
    abmahnungLoggedProb: 0.91,
  },
  {
    id: 238,
    name: "Waltraud Sauer",
    jobTitle: "Senior Controllerin",
    department: "Finanzen",
    yearsInCompany: 11,
    performanceScore: 4.6,
    lastReviewSummary:
      "Exzellente Finanzanalysen und Budgetkontrolle, strategische Beraterin.",
    scenario: "Entwicklung neuer Finanz-KPIs.",
    supervisorAgreesRaiseProb: 0.75,
    hrApprovesFireProb: 0.05,
    abmahnungLoggedProb: 0.98,
  },
  {
    id: 239,
    name: "Alfred Kern",
    jobTitle: "Team Lead Frontend Entwicklung",
    department: "Technologie",
    yearsInCompany: 7,
    performanceScore: 4.5,
    lastReviewSummary:
      "Starke technische Führung, motiviert das Frontend-Team.",
    scenario: "Auswahl eines neuen JavaScript-Frameworks.",
    supervisorAgreesRaiseProb: 0.7,
    hrApprovesFireProb: 0.07,
    abmahnungLoggedProb: 0.96,
  },
  {
    id: 240,
    name: "Hildegard Busch",
    jobTitle: "Lohnbuchhalterin",
    department: "Personalwesen",
    yearsInCompany: 9,
    performanceScore: 4.3,
    lastReviewSummary:
      "Sehr erfahren und genau bei der Gehaltsabrechnung, kennt alle Sonderfälle.",
    scenario: "Einarbeitung einer neuen Kollegin.",
    supervisorAgreesRaiseProb: 0.6,
    hrApprovesFireProb: 0.08,
    abmahnungLoggedProb: 0.93,
  },
  {
    id: 241,
    name: "Reinhard Arnold",
    jobTitle: "Softwareentwickler",
    department: "Technologie",
    yearsInCompany: 4,
    performanceScore: 4.0,
    lastReviewSummary: "Zuverlässig, liefert Code termingerecht.",
    scenario: "Standardmäßiger Leistungsbeurteilungszyklus.",
    supervisorAgreesRaiseProb: 0.5,
    hrApprovesFireProb: 0.1,
    abmahnungLoggedProb: 0.9,
  },
  {
    id: 242,
    name: "Irmgard Wolff",
    jobTitle: "IT-Projektkoordinatorin",
    department: "Projektmanagement",
    yearsInCompany: 2,
    performanceScore: 3.6,
    lastReviewSummary:
      "Organisiert gut, benötigt mehr Sicherheit im Umgang mit Stakeholdern.",
    scenario: "Teilnahme an Kommunikationsschulung.",
    supervisorAgreesRaiseProb: 0.3,
    hrApprovesFireProb: 0.15,
    abmahnungLoggedProb: 0.86,
  },
  {
    id: 243,
    name: "Wilhelm Kuhn",
    jobTitle: "Systemadministrator",
    department: "IT-Infrastruktur",
    yearsInCompany: 10,
    performanceScore: 3.7,
    lastReviewSummary:
      "Hält Altsysteme am Laufen, wenig Interesse an neuen Technologien.",
    scenario: "Diskussion über Weiterbildung und Modernisierung.",
    supervisorAgreesRaiseProb: 0.35,
    hrApprovesFireProb: 0.17,
    abmahnungLoggedProb: 0.8,
  },
  {
    id: 244,
    name: "Christa Ziegler",
    jobTitle: "Vertriebsassistenz",
    department: "Vertrieb",
    yearsInCompany: 3,
    performanceScore: 3.9,
    lastReviewSummary:
      "Unterstützt das Team gut, könnte CRM-System besser nutzen.",
    scenario: "CRM-System Schulung.",
    supervisorAgreesRaiseProb: 0.45,
    hrApprovesFireProb: 0.11,
    abmahnungLoggedProb: 0.88,
  },
  {
    id: 245,
    name: "Gerhard Kraft",
    jobTitle: "Junior DevOps Engineer",
    department: "Technologie",
    yearsInCompany: 1,
    performanceScore: 3.8,
    lastReviewSummary: "Sehr lernwillig im Bereich Automatisierung und Cloud.",
    scenario: "Erstes Jahresgespräch.",
    supervisorAgreesRaiseProb: 0.4,
    hrApprovesFireProb: 0.12,
    abmahnungLoggedProb: 0.9,
  },
  {
    id: 246,
    name: "Edith Keller",
    jobTitle: "UI Designerin",
    department: "Design",
    yearsInCompany: 4,
    performanceScore: 4.2,
    lastReviewSummary: "Erstellt ansprechende und konsistente UI-Komponenten.",
    scenario: "Überarbeitung des Design Systems.",
    supervisorAgreesRaiseProb: 0.6,
    hrApprovesFireProb: 0.1,
    abmahnungLoggedProb: 0.92,
  },
  {
    id: 247,
    name: "Helmut Grimm",
    jobTitle: "IT-Support Spezialist",
    department: "Support",
    yearsInCompany: 2,
    performanceScore: 2.8,
    lastReviewSummary:
      "Mehrere Beschwerden über Unfreundlichkeit, Lösungszeiten zu lang.",
    scenario: "Formale Abmahnung wegen wiederholter Probleme.",
    supervisorAgreesRaiseProb: 0.05,
    hrApprovesFireProb: 0.6,
    abmahnungLoggedProb: 0.65,
  },
  {
    id: 248,
    name: "Ruth Hess",
    jobTitle: "Personalreferentin (Compensation & Benefits)",
    department: "Personalwesen",
    yearsInCompany: 6,
    performanceScore: 4.4,
    lastReviewSummary:
      "Entwicklung fairer Gehaltsstrukturen, gute Marktkenntnisse.",
    scenario: "Analyse der Gehaltsbenchmarks.",
    supervisorAgreesRaiseProb: 0.65,
    hrApprovesFireProb: 0.07,
    abmahnungLoggedProb: 0.95,
  },
  {
    id: 249,
    name: "Josef Ernst",
    jobTitle: "Softwareentwickler",
    department: "Technologie",
    yearsInCompany: 7,
    performanceScore: 4.6,
    lastReviewSummary:
      "Sehr produktiv, schreibt sauberen und gut getesteten Code.",
    scenario: "Antrag auf außerplanmäßige Gehaltserhöhung.",
    supervisorAgreesRaiseProb: 0.7,
    hrApprovesFireProb: 0.06,
    abmahnungLoggedProb: 0.97,
  },
  {
    id: 250,
    name: "Lieselotte Meier",
    jobTitle: "Projektmanagerin",
    department: "Projektmanagement",
    yearsInCompany: 9,
    performanceScore: 4.0,
    lastReviewSummary:
      "Erfahren, aber manchmal zu detailverliebt, was zu Verzögerungen führt.",
    scenario: "Diskussion über Priorisierung und Delegation.",
    supervisorAgreesRaiseProb: 0.5,
    hrApprovesFireProb: 0.1,
    abmahnungLoggedProb: 0.88,
  },
  {
    id: 251,
    name: "Roland Kurz",
    jobTitle: "Netzwerkadministrator",
    department: "IT-Infrastruktur",
    yearsInCompany: 4,
    performanceScore: 4.3,
    lastReviewSummary: "Sorgt für hohe Netzwerkverfügbarkeit und -sicherheit.",
    scenario: "Implementierung eines neuen Monitoring-Tools.",
    supervisorAgreesRaiseProb: 0.6,
    hrApprovesFireProb: 0.09,
    abmahnungLoggedProb: 0.93,
  },
  {
    id: 252,
    name: "Elfriede Graf",
    jobTitle: "Auszubildende Mediengestalterin Digital und Print",
    department: "Design",
    yearsInCompany: 1,
    performanceScore: 3.7,
    lastReviewSummary:
      "Kreativ und lernbereit, unterstützt bei Grafikerstellung.",
    scenario: "Erstes Ausbildungsjahr abgeschlossen.",
    supervisorAgreesRaiseProb: 0.3,
    hrApprovesFireProb: 0.15,
    abmahnungLoggedProb: 0.9,
  },
  {
    id: 253,
    name: "Manfred Braun",
    jobTitle: "Vertriebsleiter",
    department: "Vertrieb",
    yearsInCompany: 10,
    performanceScore: 4.8,
    lastReviewSummary:
      "Führt das Vertriebsteam zu konstanten Erfolgen, strategische Ausrichtung.",
    scenario: "Jahresplanung Vertriebsziele.",
    supervisorAgreesRaiseProb: 0.8,
    hrApprovesFireProb: 0.04,
    abmahnungLoggedProb: 0.99,
  },
  {
    id: 254,
    name: "Gertrud Krause",
    jobTitle: "Senior Recruiterin",
    department: "Personalwesen",
    yearsInCompany: 8,
    performanceScore: 4.5,
    lastReviewSummary:
      "Exzellentes Netzwerk, besetzt auch Führungspositionen erfolgreich.",
    scenario: "Entwicklung einer Employer Branding Strategie.",
    supervisorAgreesRaiseProb: 0.7,
    hrApprovesFireProb: 0.06,
    abmahnungLoggedProb: 0.96,
  },
  {
    id: 255,
    name: "Horst Petersen",
    jobTitle: "Software Architekt",
    department: "Technologie",
    yearsInCompany: 12,
    performanceScore: 4.7,
    lastReviewSummary:
      "Definiert robuste und skalierbare Architekturen, berät Teams.",
    scenario: "Review der technischen Roadmap.",
    supervisorAgreesRaiseProb: 0.8,
    hrApprovesFireProb: 0.05,
    abmahnungLoggedProb: 0.98,
  },
  {
    id: 256,
    name: "Brigitte Beck",
    jobTitle: "Chief Marketing Officer (CMO)",
    department: "Management",
    yearsInCompany: 5,
    performanceScore: 4.9,
    lastReviewSummary:
      "Erfolgreiche Neuausrichtung der Marketingstrategie, starkes Markenwachstum.",
    scenario: "Vorstellung der Marketingergebnisse vor dem Vorstand.",
    supervisorAgreesRaiseProb: 0.9,
    hrApprovesFireProb: 0.03,
    abmahnungLoggedProb: 0.99,
  },
];
